version: '3.9'

x-restart-policy: &restart-policy
  restart: unless-stopped

x-logging-config: &logging-config
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '100M'


networks:
  backend:
    driver: bridge

services:
  yovisto:
    container_name: yovisto
    build:
      context: .
      network: host
    image: docker.edu-sharing.com/projects/oeh-redaktion/edusharing-projects-oeh-redaktion-yovisto:dev
    <<: *restart-policy
    <<: *logging-config
    environment:
      ROOT_PATH: ""
      ALLOWED_HOSTS: "${ALLOWED_HOSTS:-*}"
      LOG_LEVEL: "${LOG_LEVEL:-debug}"
      LOGGER: uvicorn
      WANT_RETRAINING: "${WANT_RETRAINING:-false}"
    command: bash -c "uvicorn --host 0.0.0.0 --port 8082 --reload main:app"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/_ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - backend
