version: '3.9'

x-restart-policy: &restart-policy
  restart: unless-stopped

x-logging-config: &logging-config
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '100M'

services:
  yovisto:
    container_name: yovisto
    build:
      context: .
      network: host
    image: docker.edu-sharing.com/projects/oeh-redaktion/edusharing-projects-oeh-redaktion-yovisto:dev
    <<: *restart-policy
    <<: *logging-config
    expose:
      - 8080
    environment:
      ROOT_PATH: "/api"
      API_VERSION: "${API_VERSION:-v1}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS:-*}"
      LOG_LEVEL: "${LOG_LEVEL:-debug}"
      LOGGER: uvicorn
      WEB_CONCURRENCY: 1
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
