name: Yovisto push actions

on:
  push:

env:
  docker_repository: "docker.edu-sharing.com"
  path_prefix: "/projects/wlo/edu_sharing-projects-wlo-yovisto"


jobs:
  build-and-push:
    name: Build and Push Yovisto topics image to community edu hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to EDU-Sharing Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.docker_repository }}
          username: ${{ secrets.DOCKER_EDU_HUB_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_EDU_HUB_REGISTRY_PASSWORD }}
      - uses: rlespinasse/github-slug-action@v4
      - name: Build
        run: docker build -t ${{env.docker_repository}}${{env.path_prefix}}:${{ env.GITHUB_REF_SLUG }} .
      - name: Push
        run: docker push ${{env.docker_repository}}${{env.path_prefix}}:${{ env.GITHUB_REF_SLUG }}


  python-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.8"
          cache: 'poetry'
      - name: build artifact and install
        run: |
          poetry env use 3.10
          poetry install
          poetry run python -c "import nltk;nltk.download('stopwords')"
      - name: run pre-commit hooks
        run: poetry run pre-commit run --all-file
      - name: run pytest
        run: poetry run pytest
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: |
            dist/*.whl
